
services:
  - docker

script:
  - docker build . -t tramm/dms
  - docker run -d -p 127.0.0.1:80:4567 tramm/dms
  - docker ps -a

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
 
notifications:
  slack: saboogroupworkspace:tco87KFtlVfRyVKhQoaEfKQn
  