
services:
  - docker

script:
  - docker build . -t tramm/dms
  - docker run -d -p 127.0.0.1:80:4567 tramm/dms
  - docker ps -a

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push $DOCKER_USERNAME/dms:$TRAVIS_BUILD_NUMBER
 
notifications:
  slack: saboogroupworkspace:tco87KFtlVfRyVKhQoaEfKQn
  