
services:
  - docker

before_install:
  - docker build . -t tramm/dms
  - docker run -d -p 127.0.0.1:80:4567 tramm/dms
  - docker ps -a

notifications:
  slack: saboogroupworkspace:tco87KFtlVfRyVKhQoaEfKQn
  